# Generated by Django 5.1.5 on 2025-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
                ('opcion1', models.CharField(max_length=100)),
                ('opcion2', models.CharField(max_length=100)),
                ('opcion3', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas')),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
    ]
