# Generated by Django 5.1.5 on 2025-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='materia',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion1',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion2',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion3',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.CharField(max_length=5000),
        ),
    ]
