# Generated by Django 5.1.5 on 2025-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_preguntas_materia_alter_preguntas_opcion1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntas',
            old_name='imagen',
            new_name='preguntaImagen',
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='materia',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='opcion3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
