# Generated by Django 5.1.5 on 2025-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_rename_imagen_preguntas_preguntaimagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='preguntaImagen',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to=''),
        ),
    ]
