# Generated by Django 5.1.5 on 2025-01-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_preguntas_preguntaimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='preguntaImagen',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
