# Generated by Django 5.1.5 on 2025-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_alter_preguntas_preguntaimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
                ('Puntaje', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
    ]
