# Generated by Django 5.1.5 on 2025-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_jugadores_delete_preguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='Nombre',
            field=models.CharField(max_length=15),
        ),
    ]
