# Generated by Django 5.1.5 on 2025-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_jugadores_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='ModoDeJuego',
            field=models.CharField(default='No Data', max_length=30),
            preserve_default=False,
        ),
    ]
